### PR TITLE
Use namedtuple to store params

### PR DESCRIPTION
**Pull request by serebrov**
One more option to aviod problems with dictionary (string keys) - use `namedtuple` to store the params.

### CODE REVIEW

**Comment by al-serebrov** [comment]
Yeah, this option seems to be the best... Simpler than option with `kwargs` and much more elegant than mine with `OrderedDict`. Superb!
Let's go with this one?

**Comment by serebrov** [comment]
@al-serebrov yes, I think this is a good one, I actually started the `opt3` change with something like this - https://github.com/al-serebrov/python-auto-ria/pull/14/commits/0fb3f6f1d4bea9a5cde65f5a42ec5d6310ab4dfd, using the separate class to store the parameters, but then switched to different solution.
So that was one more option - use separate class for parameters (although `namedtuple` fits very good here and it already has the `_asdict` method).

**Comment by al-serebrov** [comment]
@serebrov and as far as I understood `collections.namedtyple` is a class that we're instantiating, so technically we have a separate object with parameters :smile:

**Comment by serebrov** [comment]
@al-serebrov yes that is right, I mean the standard class vs our own class for parameters. Basically, this is the same solution.

**Pull request merged**
